# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI/CD Pipeline with Maven

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  release:
    env: 
      COMMIT_MESSAGE: ${{ github.event.head_commit.message }} | cut -d '-' -f 1
    runs-on: ubuntu-latest
    needs: build
    
    steps: 
    
      - name: Download artifacts
        uses: actions/download-artifact@v2.0.10
        with:
          name: catshop
          
      - name: Archive artifacts
        uses: thedoctor0/zip-release@master
        with:
          filename: catshop.zip
          
      - name: Create GitHub release
        id: create-new-release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v$"${COMMIT_MESSAGE}"
          release_name: Release V"${COMMIT_MESSAGE}"
          
      - name: Upload artifact to GitHub release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create-new-release.outputs.upload_url }}
          asset_path: ./catshop.zip
          asset_name: catshop-v"${COMMIT_MESSAGE}".zip
          asset_content_type: application/zip

  build:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macOS-latest]
        
    steps:
    - uses: actions/checkout@v2  
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
        
    - name: Build and Install with Maven
      run: make
      
    - name: Prepare artifacts for distribution
      run: |
        mkdir staging
        cp *.jar staging
        cp DataBase.txt staging
        cp -r images staging
        ls staging
        
    - name: Distirbute artifacts
      uses: actions/upload-artifact@v2
      with:
        name: catshop
        path: staging
        
